/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppEarth {}
  interface GdGlobe {}
}

declare global {


  interface HTMLAppEarthElement extends Components.AppEarth, HTMLStencilElement {}
  var HTMLAppEarthElement: {
    prototype: HTMLAppEarthElement;
    new (): HTMLAppEarthElement;
  };

  interface HTMLGdGlobeElement extends Components.GdGlobe, HTMLStencilElement {}
  var HTMLGdGlobeElement: {
    prototype: HTMLGdGlobeElement;
    new (): HTMLGdGlobeElement;
  };
  interface HTMLElementTagNameMap {
    'app-earth': HTMLAppEarthElement;
    'gd-globe': HTMLGdGlobeElement;
  }
}

declare namespace LocalJSX {
  interface AppEarth {
    'onInit'?: (event: CustomEvent<any>) => void;
  }
  interface GdGlobe {}

  interface IntrinsicElements {
    'app-earth': AppEarth;
    'gd-globe': GdGlobe;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-earth': LocalJSX.AppEarth & JSXBase.HTMLAttributes<HTMLAppEarthElement>;
      'gd-globe': LocalJSX.GdGlobe & JSXBase.HTMLAttributes<HTMLGdGlobeElement>;
    }
  }
}


