/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppScene {}
}

declare global {


  interface HTMLAppSceneElement extends Components.AppScene, HTMLStencilElement {}
  var HTMLAppSceneElement: {
    prototype: HTMLAppSceneElement;
    new (): HTMLAppSceneElement;
  };
  interface HTMLElementTagNameMap {
    'app-scene': HTMLAppSceneElement;
  }
}

declare namespace LocalJSX {
  interface AppScene {}

  interface IntrinsicElements {
    'app-scene': AppScene;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-scene': LocalJSX.AppScene & JSXBase.HTMLAttributes<HTMLAppSceneElement>;
    }
  }
}


