/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface GdGlobe {}
  interface GdSatellite {
    'name': string;
    'noradId': number;
  }
}

declare global {


  interface HTMLGdGlobeElement extends Components.GdGlobe, HTMLStencilElement {}
  var HTMLGdGlobeElement: {
    prototype: HTMLGdGlobeElement;
    new (): HTMLGdGlobeElement;
  };

  interface HTMLGdSatelliteElement extends Components.GdSatellite, HTMLStencilElement {}
  var HTMLGdSatelliteElement: {
    prototype: HTMLGdSatelliteElement;
    new (): HTMLGdSatelliteElement;
  };
  interface HTMLElementTagNameMap {
    'gd-globe': HTMLGdGlobeElement;
    'gd-satellite': HTMLGdSatelliteElement;
  }
}

declare namespace LocalJSX {
  interface GdGlobe {}
  interface GdSatellite {
    'name'?: string;
    'noradId'?: number;
    'onFoundPosition'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'gd-globe': GdGlobe;
    'gd-satellite': GdSatellite;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'gd-globe': LocalJSX.GdGlobe & JSXBase.HTMLAttributes<HTMLGdGlobeElement>;
      'gd-satellite': LocalJSX.GdSatellite & JSXBase.HTMLAttributes<HTMLGdSatelliteElement>;
    }
  }
}


